FROM mysql:latest

# Set MySQL root password (change it to something secure)
ENV MYSQL_ROOT_PASSWORD=password

# Create a new database (optional)
ENV MYSQL_DATABASE=student

# Expose port 3306
EXPOSE 3306
