version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile   # Name of your custom Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
